require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "node_modules/**/*"
    - "db/**/*"
    - "vendor/**/*"
    - "lib/tasks/**/*"
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 30
Metrics/BlockLength:
  Max: 30
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 8
Rails/ApplicationController:
  Enabled: false
Rails/EnvironmentVariableAccess:
  Enabled: false
Rails/UnknownEnv:
  Environments:
    - development
    - test
RSpec/MultipleExpectations:
  Max: 3
RSpec/ExampleLength:
  Max: 10
Rails/I18nLocaleTexts:
  Enabled: false
RSpec/NestedGroups:
  Max: 5
RSpec/MultipleMemoizedHelpers:
  Max: 10
RSpec/MessageSpies:
  EnforcedStyle: receive
RSpec/AnyInstance:
  Enabled: false
RSpec/FactoryBot/SyntaxMethods:
  Enabled: false
