version: 2.1
orbs:
  rubocop: hanachin/rubocop@0.0.6

workflows:
  test:
    jobs:
      - rubocop/rubocop:
          after-install-rubocop:
            - run: gem install rubocop-performance
            - run: gem install rubocop-rails
            - run: gem install rubocop-rspec
          version: "1.26"

