version: 2.1
executors:
  default_container:
    docker:
      - image: cimg/ruby:3.1.1-node
    working_directory: ~/testrubocopci
commands:
  install_bundler:
    description: Bundler install
    steps:
      - run: gem install bundler -v 2.3.7

jobs:
  fetch_source_code:
    executor:
      name: default_container
    steps:
      - checkout
      - save_cache:
          key: v1 -testrubocopci-{{.Environment.CIRCLE_SHA1}}
          paths:
            - ~/testrubocopci

  rubocop:
    executor:
      name: default_container
    steps:
      - restore_cache:
          key: v1 -testrubocopci-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1 -dependencies-{{ checksum "Gemfile.lock" }}
      - install_bundler
      - run:
          name: Bundle Install Dependencies
          command: |
            bundle install
      - run:
          name: Execute rubocop
          command: |
            bundle exec rubocop

workflows:
  build:
    jobs:
      - fetch_source_code
      - rubocop:
          requires:
            - fetch_source_code
