version: 2.1

jobs:
  rubocop:
    docker:
      - image: cimg/ruby:3.1.1-node
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: |
            gem install bundler -v 2.3.7
      - run:
          name: Bundle Install Dependencies
          command: |
            bundle install
      - run:
          name: Execute rubocop
          command: |
            bundle exec rubocop

workflows:
  rubocop-workflow:
    jobs:
      - rubocop
