version: 2.1
orbs:
  rubocop: hanachin/rubocop@0.0.6
  node: circleci/node@5.0.2
  ruby: circleci/ruby@1.0

jobs:
  test:
    docker:
      - image: cimg/ruby:2.7-node
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: whirl
          POSTGRES_DB: whirl_test
          POSTGRES_PASSWORD: ""
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: whirl
      PGPASSWORD: ""
      RAILS_ENV: test

    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - ruby/rspec-test

  eslint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn lint:es
          name: Run eslint
      - run:
          command: yarn lint:sc
          name: Run stylelint

workflows:
  tests_and_linters:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - main

      - rubocop/rubocop:
          after-install-rubocop:
            - run: gem install rubocop-performance
            - run: gem install rubocop-rails
            - run: gem install rubocop-rspec
          version: "1.26"
          filters:
            branches:
              ignore:
                - main

      - eslint
          filters:
            branches:
              ignore:
                - main